Find_number_game.java

This program help us to understand 'if' statements and do-while loop.

Basic java program for logics

---

selectionSort.cpp

please add my file as hacktober fest label and acceopt it.

Added selection Sort

---

bubbleSort.java

Bubble Sort Algorithm

---

RatInAMaze.java

Added Popular Interview Problem rat in a maze

---

BellmanAlgo.java

Kindly review it and merge it and please label it hacktoberfest-accepted

adding famous bellman ford algorithm

---

leetcodeMerge2list.java

Kindly review and merge this PR and label it hacktoberfest-Accepted

Added Leetcode solution Merge to sorted lists

---

Leetcode-KthElementinBST.java

Added leetcode solution for kth element in Binary search tree
Kindly review it and merge it.

leetcode solution for kth element in BST

---

cyclic_sort.java
insertion_sort.java
selection_sort.java

Added selection sort ,Insertion sort and cyclic sort in java

---

tictactoe/LoopInLL.java

Hello @surajkr122, I have added a problem related to Tree, which will return the sum of the node range given in the problem statement.
Please do consider the problem and accept the PR request by adding “HACKTOBERFEST-ACCEPTED” label.
Thanks in advance.  😊
https://github.com/seemaPatl

Linked List problem

---

7_segment_problem.java

7 Segment Display gfg problem solution

7 Segment Display

---

BubbleSort.java
Drawcirclewithoutfloatingpointarithmetic.java

Add a new program Draw a circle without floating point arithmetic to your code.

Draw a circle without floating point arithmetic

---

number_system_conversion.py

This is a python program that can convert between various number systems like Binary, octal, hexadecimal and decimal

A python program for number system conversion

---

PasswordGenerator.java

A Password Generator with some standard arguments

Java: Password Generator

---

Suhu.java

degree converter with java

---

kadanes_Algorithm.java
prob83_leetcode_remove_duplicate.java

with full explanation with steps.

Added problem 83 of leetcode in java.

---

prob242_valid_Anagram.java
prob3_leetcode.java

To find valid anagram with explanation.

Added problem 242 of leetcode in java.

---

prob637_leetcode.java

Question: Average of Levels in Binary Tree

Added problem 637 of leetcode in java.

---

binary_Search.cpp

Contributed to Binary Search in C++. Leetcode question 704.

Binary Search

---

python_algo/integer_to_roman_numeral.py
python_algo/largest_sublist_sum.py
python_algo/only_child.py
python_algo/removing_parentheses.py
python_algo/search_in a_binary_search_tree.py

Some python solutions for medium algorithms by the hacktoberfest 2022

Some python solutions for medium algorithms level by the hacktoberfest 2022

---

27RL_Half_CharInvPyd.cpp

please merge/add my file to your repository with the label hacktoberfest. Happy Hacktoberfest-2022 bro 🎉

hacktoberfest-2022

---

digital_clock.html

Contributed digital clock using HTML, CSS and Javascript

Digital Clock

---

AgeCalculate.java

Assign this issue under Hacktoberfest 2022
#116

Created Age finding program in java

---

Dfs.java

Added Depth First Search in JAVA

DepthFirstSearch
